name: NAME

on:
  push:
    branches:
      - main
    paths:
      - 'FOLDER/**'
      - 'common/**'
      - 'package.json'
    tags:
      - 'preview/NAME-v*'
      - 'release/NAME-v*'

jobs:
  testing:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/.deploy_worlds.yml
    with:
      directory: FOLDER
      worlds: WORLDS
    secrets:
      DEPLOY_PKEY: ${{ secrets.WORLDS_PKEY }}

  staging:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/.deploy_genesis.yml
    with:
      directory: FOLDER
      coordinates: '[""]'
      mainnet: ${{ startsWith(github.ref_name, 'release') }}
    secrets:
      DEPLOY_PKEY: ${{ secrets.GENESIS_PKEY }}
