name: .deploy-genesis

on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: .
      coordinates:
        required: true
        type: string
      mainnet:
        type: boolean
        default: false
    secrets:
      DEPLOY_PKEY:
        required: true

env:
  testing-server: linker-server.decentraland.today
  production-server: linker-server.decentraland.org

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        working-directory: ./
        run: npm install
      - name: build project
        run: npm run build -- --production --skip-install
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          include-hidden-files: true
          name: project
          path: |
            ./${{ inputs.directory }}
            !./${{ inputs.directory }}/node_modules
  staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v4
      - name: install decentraland cli
        run: npm install -g decentraland
      - uses: actions/download-artifact@v4
        with:
          name: project
      - name: set genesis coordinates
        run: node -e '${{ vars.SET_DEPLOY_TARGET }}' genesis '${{ inputs.coordinates }}'
      - name: deploy to testing catalyst
        env:
          DCL_PRIVATE_KEY: ${{ secrets.DEPLOY_PKEY }}
        run: dcl deploy -t ${{ env.testing-server }} --skip-build --skip-validations --skip-version-checks

  production:
    needs: staging
    runs-on: ubuntu-latest
    environment: production
    if: inputs.mainnet
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/download-artifact@v4
        with:
          name: project
      - run: npm install @dcl/sdk-commands
      - name: set genesis coordinates
        run: node -e '${{ vars.SET_DEPLOY_TARGET }}' genesis '${{ inputs.coordinates }}'
      - name: deploy to mainnet catalyst
        # env:
        #   DCL_PRIVATE_KEY: ${{ secrets.DEPLOY_PKEY }}
        run: npm run deploy -- -t ${{ env.production-server }} --skip-build --skip-validations --skip-version-checks
