name: .deploy-worlds

on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: .
      worlds:
        required: true
        type: string
    secrets:
      DEPLOY_PKEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        working-directory: ./
        run: npm install
      - name: build project
        run: npm run build -- --production --skip-install
      - name: set worlds name
        run: node -e '${{ vars.SET_DEPLOY_TARGET }}' worlds '${{ inputs.worlds }}'
      - name: deploy to worlds
        env:
          DCL_PRIVATE_KEY: ${{ secrets.DEPLOY_PKEY }}
        run: npm run deploy -- --skip-build --target-content https://worlds-content-server.decentraland.org
