name: deploy-genesis

on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: .
      server:
        required: true
        type: string
    secrets:
      DEPLOY_PKEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dcl
        run: npm install -g decentraland
      - name: install dependencies
        working-directory: ./
        run: npm install --workspaces=true && pwd && ls ./node_modules/@dcl-sdk
      - name: build
        run: npm run build -- --production --skip-install
      - name: deploy to genesis
        env:
          DCL_PRIVATE_KEY: ${{ secrets.DEPLOY_PKEY }}
        run: dcl deploy -t ${{ inputs.server }} --skip-build --skip-validations --skip-version-checks
