name: deploy-genesis

on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: .
      server:
        required: true
        type: string
    secrets:
      DEPLOY_PKEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        working-directory: ./
        run: npm install
      - name: build project
        run: npm run build -- --production --skip-install
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          include-hidden-files: true
          path: |
            ./
            !src
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install decentraland cli
        run: npm install -g decentraland
      - uses: actions/download-artifact@v4
      - run: ls -la
      - name: deploy to genesis
        env:
          DCL_PRIVATE_KEY: ${{ secrets.DEPLOY_PKEY }}
        run: dcl deploy -t ${{ inputs.server }} --skip-build --skip-validations --skip-version-checks
