name: deploy-genesis

on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: .
      server:
        required: true
        type: string
    secrets:
      DEPLOY_PKEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.directory }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install dcl
        run: npm install dcl
      - name: install root dependencies
        if: inputs.directory != '.'
        working-directory: ./
        run: npm install
      - name: install project dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: deploy to genesis
        env:
          DCL_PRIVATE_KEY: ${{ secrets.DEPLOY_PKEY }}
        run: dcl deploy -t ${{ inputs.server }} --skip-build --skip-validations
