name: gears
on:
  push:
    branches:
      - main
    paths:
      - 'SpotTheDifference/**'
      - 'common/**'
    tags:
      - 'preview/gears-v*'
      - 'release/gears-v*'

jobs:
  testing:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/.deploy_worlds.yml
    with:
      directory: SpotTheDifference
      worlds: v01d.crossverse.eth
    secrets:
      DEPLOY_PKEY: ${{ secrets.WORLDS_PKEY }}

  release:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/.deploy_genesis.yml
    with:
      directory: SpotTheDifference
      coordinates: '["-138,-94"]'
      mainnet: ${{ startsWith(github.ref_name, 'release') }}
    secrets:
      DEPLOY_PKEY: ${{ secrets.GENESIS_PKEY }}
