name: laser

on:
  push:
    branches:
      - main
    paths:
      - 'Laser/**'
      - 'common/**'
      - 'package.json'
    tags:
      - 'preview/laser-v*'
      - 'release/laser-v*'

jobs:
  testing:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/.deploy_worlds.yml
    with:
      directory: Laser
      worlds: hunter.crossverse.eth
    secrets:
      DEPLOY_PKEY: ${{ secrets.WORLDS_PKEY }}

  staging:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/.deploy_genesis.yml
    with:
      directory: Laser
      coordinates: '[""]'
      mainnet: ${{ startsWith(github.ref_name, 'release') }}
    secrets:
      DEPLOY_PKEY: ${{ secrets.GENESIS_PKEY }}
