name: match-two

on:
  push:
    branches:
      - main
      - ci_tests
    paths:
      - 'MatchTwo/**'
      - 'common/**'
    tags:
      - 'stage/match-v*'

jobs:
  testing:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/deploy_worlds.yml
    with:
      directory: MatchTwo
      worlds: snikes.crossverse.eth
    secrets:
      DEPLOY_PKEY: ${{ secrets.WORLDS_PKEY }}

  staging:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/deploy_genesis.yml
    with:
      directory: MatchTwo
      server: linker-server.decentraland.today
      coordinates: '["50,-88"]'
    secrets:
      DEPLOY_PKEY: ${{ secrets.GENESIS_PKEY }}
