name: steampunk
on:
  push:
    branches:
      - main
      - ci_tests
    paths:
      - 'SpotTheDifference/**'
      - 'common/**'
    tags:
      - 'stage/steampunk-v*'

jobs:
  testing:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/.deploy_worlds.yml
    with:
      directory: SpotTheDifference
      worlds: v01d.crossverse.eth
    secrets:
      DEPLOY_PKEY: ${{ secrets.WORLDS_PKEY }}

  staging:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/.deploy_genesis.yml
    with:
      directory: SpotTheDifference
      server: linker-server.decentraland.today
      coordinates: '["-138,-94"]'
    secrets:
      DEPLOY_PKEY: ${{ secrets.GENESIS_PKEY }}
