name: steampunk
on:
    push:
        branches:
            - main
        paths:
            - 'Steampunk/**'
            - 'common/**'
            - 'package.json'
        tags:
            - 'preview/steampunk-v*'
            - 'release/steampunk-v*'

jobs:
    testing:
        if: github.ref_type != 'tag'
        uses: ./.github/workflows/.deploy_worlds.yml
        with:
            directory: Steampunk
            worlds: v01d.crossverse.eth
        secrets:
            DEPLOY_PKEY: ${{ secrets.WORLDS_PKEY }}

    release:
        if: github.ref_type == 'tag'
        uses: ./.github/workflows/.deploy_genesis.yml
        with:
            directory: Steampunk
            coordinates: '["-138,-94"]'
            mainnet: ${{ startsWith(github.ref_name, 'release') }}
        secrets:
            DEPLOY_PKEY: ${{ secrets.GENESIS_PKEY }}
