name: deploy-room-2-scene:test

on:
  push:
    # branches:
    # - main
    # paths:
    #   - 'SpotTheDifference/**'
    #   - 'common/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.ref }} ${{github.ref_name}} ${{github.ref_type}}"
  deploy-room-scene-worlds:
    # if: github.ref_type == 'tag'
    uses: ./.github/workflows/deploy_worlds.yml
    with:
      directory: SpotTheDifference
      worlds: v01d.dcl.eth
    secrets:
      DEPLOY_PKEY: ${{ secrets.WORLDS_PKEY }}

